Repository ChwierUp/chwier-up, pull requests merged in 2024-08, with the labels that each got.

#41 feat: 라우팅 구조 변경 및 auth 정보를 통해 깃헙 프로필 사진 연동 구현
  app/(study)/article/page.tsx
  app/(study)/layout.tsx
  app/(study)/todo/page.tsx
  app/layout.tsx
  components/Header.tsx
Labels: ✨Feat

#39 style: Header 컴포넌트의 스타일을 변경된 색상 토큰 값으로 수정
  .github/PULL_REQUEST_TEMPLATE.md
  app/globals.css
  app/page.tsx
  components/Header.tsx
  components/ModeToggle.tsx
  components/ProfileButton.tsx
  package.json
  tailwind.config.ts
Labels: 💄Style

#34 style: 투두 페이지 색상 토큰 적용
  app/(study)/todo/_components/CategorySelector.tsx
  app/(study)/todo/_components/ProgressBar.tsx
  app/(study)/todo/_components/TodoCard.tsx
  app/(study)/todo/_components/TodoCompleteButton.tsx
  app/(study)/todo/_components/TodoItem.tsx
  app/(study)/todo/_components/TodoSection.tsx
  app/(study)/todo/page.tsx
  app/globals.css
  components/DatePicker.tsx
  components/DateSlider.tsx
  components/calendar.tsx
  components/select.tsx
  pnpm-lock.yaml
  tailwind.config.ts
Labels: 💄Style

#46 refactor: axios 요청시 응답값으로 data만 보내주도록 수정
  services/core.ts
Labels: 🛠️Refactor

#32 feat: 아티클 페이지 DB, API 구축
  app/api/articles/create/route.ts
  app/api/articles/delete/route.ts
  app/api/articles/route.ts
  app/api/getOgData/route.ts
  prisma/schema.prisma
  types/dto/OgData.ts
  types/dto/article.ts
Labels: ✨Feat

#18 feat: 카테고리 선택 메뉴 컴포넌트 구현
  components/category-select-menu/CategoryMenuItem.tsx
  components/category-select-menu/CategorySelectMenu.tsx
  components/radio-group.tsx
  package.json
  pnpm-lock.yaml
Labels: ✨Feat

#17 feat: 내 글만 보기 스위치 컴포넌트 구현
  components/my-article-switch/MyArticleSwitch.tsx
  components/switch.tsx
  package.json
Labels: ✨Feat
